apiVersion: v1
kind: Pod
metadata:
   name: apache-cpu
spec:
   containers:
      - name: apache
        image: httpd
        ports:
         - containerPort: 80
        resources:
            requests:
               cpu: "0.5"
            limits:
               cpu: "1"
     