apiVersion: v1
kind: Pod
metadata:
   name: apache-memory
spec:
   containers:
      - name: apache
        image: httpd
        ports:
         - containerPort: 80
        resources:
            requests:
               memory: "100Mi"
            limits:
               memory: "200Mi"
     