apiVersion: v1
kind: Pod
metadata:
   name: fullstack
spec:
   containers:
      - name: apache
        image: httpd
        ports:
         - containerPort: 80
      - name: database
        image: ubuntu
        ports:
         - containerPort: 7501
        command: ["/bin/sh", "-ec", "sleep 1000"] 