apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels:
    app: apache
    tier: frontend
    env: dev
spec:
  containers:
    - name: apache-container
      image: httpd
      ports:
        - containerPort: 80
