apiVersion: v1
kind: Pod
metadata:
  name: database-pod
  labels:
    env: dev
spec:
  containers:
    - name: db-container
      image: ubuntu
      ports:
        - containerPort: 80
      command: ["/bin/sh", "-ec", "sleep 1000"]
