---
  - hosts: training
    remote_user: ubuntu
    become: true
    gather_facts: no
    check_mode: no
    ignore_errors: true
    tasks:
        - name: Install apache
          apt:
            name: apache2
            state: present
          notify: start-restart-stopped apache
    handlers: 
        - name: start-restart-stopped apache
          service: 
            name: apache2
            state: restarted